# Generated by Django 3.1.3 on 2021-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_order_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(default='anonimo', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(default='(593) 099 203 - 302', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
