# Generated by Django 3.1.3 on 2021-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210115_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True), null=True),
        ),
    ]
